In [1]:
import numpy as np

In [2]:
#this function prints also the result step by step
def Merge(A,p,q,r):
    n1=q-p+1
    n2=r-q
    L=np.zeros(n1+1)
    R=np.zeros(n2+1)
    for i in range(n1):
        L[i]=A[p+i]
    for j in range(n2):
        R[j]=A[q+j+1]
    L[n1]=float('inf')
    R[n2]=float('inf')
    i=0
    j=0
    for k in np.arange(p,r+1,1):
        if L[i]<=R[j]:
            A[k]=L[i]
            i=i+1
        else:
            A[k]=R[j]
            j=j+1
    print('Merge routine:\n\t', A[np.arange(p,r+1,1)])
            
def MergeSort(A,p,r,n):
    if p<r:
        q=int((p+r)/2)
        print('Step', n, '\t-->\tL=', A[np.arange(p,q+1,1)], '\tR=', A[np.arange(q+1,r+1,1)])
        MergeSort(A,p,q,n+1)
        MergeSort(A,q+1,r,n+1)
        Merge(A,p,q,r)

In [3]:
A = np.array([4, 6, 1, 3, 9, 7, 10, 8])
print('Input array, before sorting:\n\t', A, '\n')
MergeSort(A,0,len(A)-1,1)
print('\nOutput array, after sorting:\n\t', A)

Input array, before sorting:
	 [ 4  6  1  3  9  7 10  8] 

Step 1 	-->	L= [4 6 1 3] 	R= [ 9  7 10  8]
Step 2 	-->	L= [4 6] 	R= [1 3]
Step 3 	-->	L= [4] 	R= [6]
Merge routine:
	 [4 6]
Step 3 	-->	L= [1] 	R= [3]
Merge routine:
	 [1 3]
Merge routine:
	 [1 3 4 6]
Step 2 	-->	L= [9 7] 	R= [10  8]
Step 3 	-->	L= [9] 	R= [7]
Merge routine:
	 [7 9]
Step 3 	-->	L= [10] 	R= [8]
Merge routine:
	 [ 8 10]
Merge routine:
	 [ 7  8  9 10]
Merge routine:
	 [ 1  3  4  6  7  8  9 10]

Output array, after sorting:
	 [ 1  3  4  6  7  8  9 10]
