In [1]:
import numpy as np
import sys

In [2]:
def IncrMatrixMult(A,B):
    if np.shape(A)[0]!=np.shape(A)[1] or np.shape(B)[0]!=np.shape(B)[1]:
        print('One of the two matrix has a different number of rows and columns!')
        sys.exit()
    if len(A)!=len(B):
        print('The two matrix have not the same dimensions!')
        sys.exit()
    n=len(A)
    C=np.zeros(shape=(n,n))
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i][j]=C[i][j]+A[i][k]*B[k][j]
    return C

In [3]:
A=np.array([[2,3,7,1],[1,5,3,8],[8,0,1,3],[4,6,1,8]])
B=np.array([[0,0,9,3],[6,2,7,8],[5,7,1,2],[4,1,8,2]])
print('Matrix to multiply:\n')
print('A=')
print(A, '\n')
print('B=')
print(B)
print('\nResult of the matrix multiplication of A and B:\n')
print('C=')
print(IncrMatrixMult(A,B))

Matrix to multiply:

A=
[[2 3 7 1]
 [1 5 3 8]
 [8 0 1 3]
 [4 6 1 8]] 

B=
[[0 0 9 3]
 [6 2 7 8]
 [5 7 1 2]
 [4 1 8 2]]

Result of the matrix multiplication of A and B:

C=
[[ 57.  56.  54.  46.]
 [ 77.  39. 111.  65.]
 [ 17.  10.  97.  32.]
 [ 73.  27. 143.  78.]]
