In [1]:
import numpy as np
import sys

In [2]:
def Part(A):
    n=len(A)
    A11=np.zeros(shape=(int(n/2),int(n/2)))
    A12=np.zeros(shape=(int(n/2),int(n/2)))
    A21=np.zeros(shape=(int(n/2),int(n/2)))
    A22=np.zeros(shape=(int(n/2),int(n/2)))
    for i in range(int(n/2)):
        for j in range(int(n/2)):
            A11[i][j]=A[i][j]
            A12[i][j]=A[i][j+int(n/2)]
            A21[i][j]=A[i+int(n/2)][j]
            A22[i][j]=A[i+int(n/2)][j+int(n/2)]
    return A11,A12,A21,A22

def Merge(C11,C12,C21,C22):
    n=len(C11)
    C=np.zeros(shape=(2*n,2*n))
    for i in range(n):
        for j in range(n):
            C[i][j]=C11[i][j]
            C[i][j+n]=C12[i][j]
            C[i+n][j]=C21[i][j]
            C[i+n][j+n]=C22[i][j]
    return C
    

def Strassen(A,B):
    if np.shape(A)[0]!=np.shape(A)[1] or np.shape(B)[0]!=np.shape(B)[1]:
        print('One of the two matrix has a different number of rows and columns!')
        sys.exit()
    if len(A)!=len(B):
        print('The two matrix have not the same dimensions!')
        sys.exit()
    if float(np.log2(len(A))).is_integer()==False:
        print('The dimension of the two matrix is not power of 2!')
        sys.exit()
    n=len(A)
    C=np.zeros(shape=(n,n))
    if n==1:
        C[0][0]=A[0][0]*B[0][0]
    else:
        A11,A12,A21,A22=Part(A)
        B11,B12,B21,B22=Part(B)
        M1=Strassen((A11+A22),(B11+B22))
        M2=Strassen((A21+A22),B11)
        M3=Strassen(A11,(B12-B22))
        M4=Strassen(A22,(B21-B11))
        M5=Strassen((A11+A12),B22)
        M6=Strassen((A21-A11),(B11+B12))
        M7=Strassen((A12-A22),(B21+B22))
        C11=M1+M4-M5+M7
        C12=M3+M5
        C21=M2+M4
        C22=M1-M2+M3+M6
        C=Merge(C11,C12,C21,C22)
    return C

In [3]:
A=np.array([[2,3,7,1],[1,5,3,8],[8,0,1,3],[4,6,1,8]])
B=np.array([[0,0,9,3],[6,2,7,8],[5,7,1,2],[4,1,8,2]])
print('Matrix to multiply:\n')
print('A=')
print(A, '\n')
print('B=')
print(B)
print('\nResult of the matrix multiplication of A and B:\n')
print('C=')
print(Strassen(A,B))

Matrix to multiply:

A=
[[2 3 7 1]
 [1 5 3 8]
 [8 0 1 3]
 [4 6 1 8]] 

B=
[[0 0 9 3]
 [6 2 7 8]
 [5 7 1 2]
 [4 1 8 2]]

Result of the matrix multiplication of A and B:

C=
[[ 57.  56.  54.  46.]
 [ 77.  39. 111.  65.]
 [ 17.  10.  97.  32.]
 [ 73.  27. 143.  78.]]
